[project]
name = "kanban"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "lighfe", email = "juliandralle@gmx.net" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.141.1",
    "opentelemetry-exporter-otlp-proto-http>=1.45.0",
    "opentelemetry-instrumentation-fastapi>=0.66b0",
    "opentelemetry-instrumentation-sqlalchemy>=0.66b0",
    "opentelemetry-sdk>=1.45.0",
    "psycopg[binary]>=3.3.5",
    "sqlalchemy>=2.0.52",
    "uvicorn[standard]>=0.52.4",
]

[project.scripts]
kanban = "kanban:main"

[build-system]
requires = ["uv_build>=0.10.5,<0.11.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "httpx>=0.28.1",
    "pytest>=9.1.1",
]
